version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t webapp-docker:latest .
      - docker tag webapp-docker:latest 632644471688.dkr.ecr.ap-south-1.amazonaws.com/webapp-docker-build:latest    
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 632644471688.dkr.ecr.ap-south-1.amazonaws.com/webapp-docker-build:latest
artifacts:
    files: imagedefinitions.json
